// <auto-generated />
using System;
using DotNetNinja.Identity.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DotNetNinja.Identity.Data.Migrations.IdentityModel.UserDb
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20200216031420_InitialUserDbMigration")]
    partial class InitialUserDbMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DotNetNinja.Identity.Domain.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2020, 2, 15, 21, 14, 20, 271, DateTimeKind.Unspecified).AddTicks(2821), new TimeSpan(0, -6, 0, 0, 0)));

                    b.Property<DateTimeOffset>("DateModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2020, 2, 15, 21, 14, 20, 276, DateTimeKind.Unspecified).AddTicks(3814), new TimeSpan(0, -6, 0, 0, 0)));

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<Guid>("Subject")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.HasKey("Id")
                        .HasName("PK_UserAccount")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasAlternateKey("Subject")
                        .HasName("AK_UserAccount_Subject");

                    b.HasIndex("UserName")
                        .HasName("UK_UserAccount_UserName");

                    b.ToTable("UserAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
